// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Sentinel.Web.Controllers
{
    public partial class GalleryController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GalleryController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected GalleryController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewGallery);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GalleryController Actions { get { return MVC.Gallery; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Gallery";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Gallery";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ViewGalleries = "ViewGalleries";
            public readonly string ViewGallery = "ViewGallery";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ViewGalleries = "ViewGalleries";
            public const string ViewGallery = "ViewGallery";
        }


        static readonly ActionParamsClass_ViewGallery s_params_ViewGallery = new ActionParamsClass_ViewGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewGallery ViewGalleryParams { get { return s_params_ViewGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewGallery
        {
            public readonly string folderName = "folderName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ViewGalleries = "ViewGalleries";
                public readonly string ViewGallery = "ViewGallery";
            }
            public readonly string ViewGalleries = "~/Views/Gallery/ViewGalleries.cshtml";
            public readonly string ViewGallery = "~/Views/Gallery/ViewGallery.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_GalleryController : Sentinel.Web.Controllers.GalleryController
    {
        public T4MVC_GalleryController() : base(Dummy.Instance) { }

        partial void ViewGalleriesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ViewGalleries()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewGalleries);
            ViewGalleriesOverride(callInfo);
            return callInfo;
        }

        partial void ViewGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string folderName);

        public override System.Web.Mvc.ActionResult ViewGallery(string folderName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "folderName", folderName);
            ViewGalleryOverride(callInfo, folderName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
